# Change these first
owner: arty01238 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Wisp Server
    url: https://vnhosts.xyz
  - name: Support Site
    url: https://www.vnhosts.net
  - name: Nerdy Megans Server
    check: "tcp-ping"
    url: 135.148.162.24
    port: 26900
  - name: Gnome Test Status
    check: "tcp-ping"
    url: 135.148.162.24
    port: 27020

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vnhosts.com
  # baseUrl: /your-repo-name
  theme: night
  favicon: https://www.vnhosts.net/assets/img/logo.png
  logoUrl: https://www.vnhosts.net/assets/img/logo.png
  name: VNHosts Status
  introTitle: "This Site Is For Status Updates For The Server!"
  introMessage: This is a status page which uses **real-time** data from our Sites.
  navbar:
    - title: VNHosts Server Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.gg/g2uG3UQPfG
    - title: Main Site
      href: https://www.vnhosts.com
    - title: Support
      href: https://www.vnhosts.net
    - title: Wisp Server Access
      href: https://vnhosts.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
